// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CookieConsentController from "./cookie_consent_controller"
application.register("cookie-consent", CookieConsentController)

import CourseAdminPreviewImageController from "./course_admin_preview_image_controller"
application.register("course-admin-preview-image", CourseAdminPreviewImageController)

import HeroCodeEditorController from "./hero_code_editor_controller"
application.register("hero-code-editor", HeroCodeEditorController)

import ProfileUpdateAvatarController from "./profile_update_avatar_controller"
application.register("profile-update-avatar", ProfileUpdateAvatarController)

import ThemeSwitcherController from "./theme_switcher_controller"
application.register("theme-switcher", ThemeSwitcherController)
