// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ProfileUpdateAvatarController from "./profile_update_avatar_controller"
application.register("profile-update-avatar", ProfileUpdateAvatarController)
