version: '3'

services:
  web:
    build: .
    tty: true
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/bundle
    depends_on:
      - database
    environment:
      - BUNDLE_PATH=/bundle/vendor #New

  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  gem_cache:
